-- AlterTable
ALTER TABLE "Friends" ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "surname" DROP DEFAULT,
ALTER COLUMN "profilePhoto" DROP DEFAULT,
ALTER COLUMN "actionNumber" DROP DEFAULT,
ALTER COLUMN "eventsAttended" DROP DEFAULT;
